name: Code Quality & Linting

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  php-lint:
    name: PHP Linting
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: json, fileinfo, pdo, mbstring, xml, curl
        coverage: none
        tools: composer:v2, cs2pr

    - name: Get Composer Cache Directory
      id: composer-cache
      run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

    - name: Cache Composer dependencies
      uses: actions/cache@v3
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: ${{ runner.os }}-composer-

    - name: Install Dependencies
      run: composer install --prefer-dist --no-progress

    - name: Create Tests Directory
      run: mkdir -p tests

    - name: Verify Directory Structure
      run: |
        echo "Checking directory structure..."
        ls -la
        echo "Content of src directory:"
        ls -la src || echo "src directory is empty or missing"

    - name: Run PHP_CodeSniffer
      run: |
        echo "Running PHP_CodeSniffer..."
        if [ -d "src" ]; then
          vendor/bin/phpcs --report=checkstyle src/ --standard=phpcs.xml | cs2pr || echo "PHP_CodeSniffer found issues"
        else
          echo "Source directory missing. Please check repository structure."
          exit 1
        fi

    - name: Run PHP-CS-Fixer
      run: |
        if [ -d "src" ]; then
          vendor/bin/php-cs-fixer fix --dry-run --diff src/
        else
          echo "Source directory missing. Skipping PHP-CS-Fixer."
        fi

    - name: Run PHPStan
      run: |
        if [ -d "src" ]; then
          vendor/bin/phpstan analyze src/ --error-format=github --no-progress
        else
          echo "Source directory missing. Skipping PHPStan."
        fi

  js-lint:
    name: JavaScript Linting
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install Dependencies
      run: npm ci

    - name: Run ESLint
      run: |
        if [ -f "$(git ls-files '*.js' '*.jsx' '*.ts' '*.tsx' | head -1)" ]; then
          npx eslint . --ext .js,.jsx,.ts,.tsx --format=stylish
        else
          echo "No JavaScript/TypeScript files found. Skipping ESLint."
        fi 